import { CSSProperties } from "react";
import { C } from "./colors";

export const styles: Record<string, CSSProperties> = {
  page: {
    fontFamily: "'Inter', sans-serif",
    background: C.bg,
    color: C.text,
    minHeight: "100vh",
    overflowX: "hidden",
  },
  gradText: {
    background: `linear-gradient(135deg, ${C.primary}, ${C.violet})`,
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    backgroundClip: "text",
  },
  btnPrimary: {
    background: `linear-gradient(135deg, ${C.primary}, ${C.accent})`,
    color: "#fff",
    border: "none",
    borderRadius: 14,
    padding: "12px 28px",
    fontFamily: "'Poppins', sans-serif",
    fontWeight: 600,
    fontSize: 15,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    boxShadow: `0 0 24px rgba(108,77,255,0.35)`,
    transition: "all 0.2s ease",
    whiteSpace: "nowrap",
  },
  btnSecondary: {
    background: C.card,
    color: C.text,
    border: `1px solid #2A3348`,
    borderRadius: 14,
    padding: "12px 28px",
    fontFamily: "'Poppins', sans-serif",
    fontWeight: 600,
    fontSize: 15,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    transition: "all 0.2s ease",
  },
  card: {
    background: C.card,
    border: `1px solid ${C.border}`,
    borderRadius: 20,
    padding: 24,
    boxShadow: "0 10px 30px rgba(0,0,0,0.35)",
  },
  glassCard: {
    background: "rgba(17,24,39,0.7)",
    border: `1px solid rgba(108,77,255,0.2)`,
    borderRadius: 20,
    backdropFilter: "blur(16px)",
    boxShadow: "0 10px 30px rgba(0,0,0,0.35)",
  },
};